spring:
  # SESSION
  session: store-type=none

  # DATA SOURCE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/develop?useSSL=false
    username: dev-user
    password: dev-pass

  # THYMELEAF
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/

# MyBatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    ROOT: INFO
