version: '3'
services:
  mysql:
    build: ./mysql/  # 左記フォルダの以下のDockerfileを利用
    ports:
      - "3306:3306" # ポートを開ける

  app:
    build: ./app/
    depends_on:
      - mysql
    ports:
      - "8080:8080"