version: '3'

services:
  web:
    image: nginx
    depends_on:
      - app
    volumes:
      - ./web/etc/nginx/conf.d/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  app:
    build: ./app
    depends_on:
      - db
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ../build/libs:/usr/local/samplewebboard
    command: java -Djava.security.egd=file:/dev/./urandom -jar /usr/local/samplewebboard/sample-web-board.jar

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-pass
      - MYSQL_DATABASE=develop
      - TZ=Asia/Tokyo
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"